//////////////////////////////////////////////////////////////////////////////
//
//  Copyright  1999 - 2016 VASCO DATA SECURITY
//  All rights reserved. http://www.vasco.com
//
//  Generated by WBCSDK_TableGenerator 4.10.0
//
//////////////////////////////////////////////////////////////////////////////

package com.vasco.digipass.sdk.utils.wbc;


public class Wb_typeIB_output_sbox_inv_enc
{
    public static final String Data01 = "e636bc2353395a898578608db7cdcb84107dfad32bf6b1df1025693bc5638200d2ccc636eea816d9811021c14a54ee1553157eb2edcb963390e33275724a4bd2a8ed69a3308dcdaf67685fd0e14e24ebc9867d016327e3f68e6b60a820d4245a92d97cc9dab580f6e82cc81603e8d407d156f2528830e98bebd9f56e7dd7cb0c3858304c1e80dc6640d8ed5b7f4b9b3c5a9d58a6db828d994edb91da5170fcd9c6b75077beded8fe696a9e0782e09ea3d1c6c46a4c2d0f9eab7b668087852225d5b51f07e0f40848672c2a0417b98d1b0afe999458bb3c309d8a08a11f2e51eb9daf49364bb28e6d310c80b18b19849a8290ecc3f04274e81d208ed2981bf998ba4c1fd53083e2de197b1de5902663f41ac736e49e8e7357b9e49d26139eee215fe05926563727afb555a50cb44e4548360a7a8e3c6b96f378f041434b5e97ff294842d1d80edc7b891abff8bf66d042bf6532995caca77ae21f5d5b278118f04fb48e218fe51b5e28920a0ee61c4332195263a3e840ff420157ceee6af7a5b06e0985e1963873cbe13ff62c244b41ae3e0589aa5dee5f207b6c483d0ec853f3a460da55b7b6f4daa4f188b4db6101e380d5ac21b1a51f621e6ae2cba0bc9541adabdf2127c53028913bff98b67b4d98daec3f12630611c2820e55b866fc469cae264f9b974430c998c3381833ea1ad0a6b64f06623789bedc78b2cad75ee444";

}
